spring:
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:postgresql://10.32.128.113:5432/ssm
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5            # 最小空闲连接数量 默认10
#      maximum-pool-size: 10      # 连接池默认最大连接数 默认10
#      idle-timeout: 30000        # 空闲时间最大存活时间
#      auto-commit: true          # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
#      pool-name: HikariCPKEFU     # 连接池名称
#      max-lifetime: 180000       # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#      connection-timeout: 30000  # 数据库连接超时时间,默认30秒，即30000
#      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    host: localhost
    port: 5672
    addresses: localhost
    username: guest
    password: guest
    #    virtual-host:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 关闭驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml # 编写复杂的sql 语句 ，mybatis-plus 对多表关联支持性差。手写xml文件{sql语句}
redisson:
  address: redis://127.0.0.1:6379
  password:
  database: 0
  poolMinIdle: 8 #最小空闲数
  poolConnTimeout: 3000 # 连接超时时间(毫秒)
  poolSize: 10 # 连接池大小
im:
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000 #心跳超时时间 单位毫秒 20000
  heartBeatWaitRetry: 3 # 心跳重试等待次数
  brokerId: 1000 # 区分服务
  loginModel: 1
  logicUrl: http://127.0.0.1:8000/v1
  #  *                多端同步模式：1 只允许一端在线，手机/电脑/web 踢掉除了本client+imel的设备
  #  *                            2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imel的非web端设备
  #  *                            3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imel的同端设备
  #  *                            4 允许所有端多设备登录 不踢任何设备


