
spring:
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static
### freemarker
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
### datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/xxl-job
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-init-sql: SELECT 1
      validation-timeout: 1000
  cloud:
    nacos:
      discovery:
        server-addr: 10.32.128.102:8848
### mail
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    from: xxx@qq.com
    password: xxx
    properties:
      mail:
        auth: true
        starttls:
          enable: true
          required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory

### xxl
xxl:
  job:
    accessToken: default_token    # xxl-job, access token
    i18n: zh_CN                   # xxl-job, i18n (default is zh_CN, and you can choose "zh_CN", "zh_TC" and "en")
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30          # log retention days

### mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

### actuator
management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false
server:
  servlet:
    context-path: /xxl-job-admin