spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  application:
#    name: test-api
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://10.32.128.113:5432/ssm
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5            # 最小空闲连接数量 默认10
      maximum-pool-size: 10      # 连接池默认最大连接数 默认10
      idle-timeout: 30000        # 空闲时间最大存活时间
      auto-commit: true          # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: HikariCPApi     # 连接池名称
      max-lifetime: 180000       # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000  # 数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: 10.32.128.102:8848
        #      config:
        #        server-addr: localhost:8848
        #        file-extension: yml #指定文件扩展名，默认为properties
        #        prefix: test-api
        #添加共享配置的dataId,如多个使用逗号分隔，并且越靠后，优先级越高
        #文件后缀名不能少，只支持yaml，yml，properies
        #        shared-dataids: common.yml
        #哪些共享配置支持动态刷新，如多个使用逗号分隔
  #        refreshable-dataids: common.yml
#  profiles:
#    active: dev
  servlet:
    multipart:
      max-file-size: 10MB         # 单个文件上传大小限制
      max-request-size: 15MB      # 多个文件上传大小限制
upload:
  location: F:/temp/
#server:
#  port: 8081
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 关闭驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml # 编写复杂的sql 语句 ，mybatis-plus 对多表关联支持性差。手写xml文件{sql语句}


